use_default_settings: true
server:
  # base_url is defined in the environment variable
  secret_key: "default-secret-key-to-be-overridden"
  limiter: false
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: "redis://immich-redis:6379/1" # Default, but will be overridden by env
search:
  safe_search: 0
  autocomplete: 'google'
  formats:
    - html
    - json
